"""user: added updated_at and last_login

Revision ID: 325888f716df
Revises: d176ccdb5a69
Create Date: 2023-08-15 23:34:40.832565

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '325888f716df'
down_revision = 'd176ccdb5a69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_login')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
