"""password renamed

Revision ID: 886224a9a7b0
Revises: 4b8fdddaf837
Create Date: 2023-08-18 09:26:36.206982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '886224a9a7b0'
down_revision = '4b8fdddaf837'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
