version: '3.8'
services:
  app:
    image: flaskapp:0.1
    hostname: flask_app
    container_name: flask_app
    build:
      dockerfile: ./Dockerfile
      context: ./
    env_file:
      - ./app/blog/config/.env
    volumes:
      - ./app/blog:/app/blog
    ports:
      - "80:8000"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    hostname: flask_db
    container_name: flask_db
    env_file:
      - ./app/blog/config/.env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/pgdata_dev:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  adminer:
    image: adminer:latest
    hostname: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
